name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

  configure-secrets:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Load Google Services file
        run: |
          echo ${{ secrets.GOOGLE_SERVICES_JSON }} | base64 -d > app/google-services.json

      - name: Load Maps API Key
        run: |
          echo -e "\nmapApiKey=\"${{ secrets.MAPS_API_KEY }}\"" >> ./local.properties

  unit-tests:
    needs: configure-secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Unit Tests
        run: ./gradlew test

  build:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build with Gradle
        run: ./gradlew build