name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Load Google Service file
        run: |
          echo "my google service secret is: ${{ secrets.GOOGLE_SERVICES_JSON }}"
          echo ${{ secrets.GOOGLE_SERVICES_JSON }} | base64 -d > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Load Maps ApiKey
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: |
          sed "s|ApiMapKey=.*|ApiMapKey=$MAPS_API_KEY|" secrets.properties > local.properties

      - name: Debug properties file
        run: |
          cat local.properties

      - name: Generate Test Build
        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Build with Gradle
        run: ./gradlew build