name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Install Command Line Tools
        run: yes | sdkmanager --install "cmdline-tools;latest" --sdk_root=${ANDROID_SDK_ROOT}

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Install Build and Platform Tools
        run: sdkmanager --install "build-tools;35.0.0" "platform-tools" "platforms;android-35"

      - name: Install System Image for API Level 33
        run: sdkmanager --install "system-images;android-33;google_apis;x86_64"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck
          emulator-boot-timeout: 600
          disable-animations: true
